const categories = [
  "HI-ZONE",
  "RC HI-ZONE",
  "MID-ZONE",
  "RC MID-ZONE",
  "UPPER-ZONE",
   "RC UPPER-ZONE",
  "LOWER-ZONE",
  "RC LOWER ZONE",
  "MIX-ZONE",
  "RC MIX-ZONE"

 
];
const sectors = ["Fath-hunoor", "Fath-hussamad", "Fath-hul kareem"];

const itemsByCategory = {
  "HI-ZONE": [
    "Qira'ath",
    "Hifz",
    "Elocution Malayalam",
    "Arabic Song",
    "Madhu Ganam",
    "Arabic Padapayatt",
    "Essay Malayalam",
    "Story Writing",
    "Quiz",
    "Qira'ath (girls)",
    "Hifz (girls)",
    "Arabic Padapayatt (girls)",
    "Essay Malayalam (girls)",
    "Story Writing (girls)",
    "Quiz (girls)",
  ],
  "MID-ZONE": [
    "Qira'ath",
    "Hifz",
    "Elocution Malayalam",
    "Arabic Song",
    "Madhu Ganam",
    "Arabic Padapayatt",
    "Essay Malayalam",
    "Calligraphy Arabic",
    "Pencil Drawing",
    "Water Coloring",
    "Quiz",
    "Kusumam Test",
    "Qira'ath (girls)",
    "Hifz (girls)",
    "Arabic Padapayatt (girls)",
    "Essay Malayalam (girls)",
    "Calligraphy Arabic (girls)",
    "Pencil Drawing (girls)",
    "Water Coloring (girls)",
    "Quiz (girls)",
  ],
  "UPPER-ZONE": [
    "Qira'ath",
    "Hifz",
    "Elocution Malayalam",
    "Arabic Song",
    "Madhu Ganam",
    "Storytelling",
    "Calligraphy",
    "Kusumam Test",
    "Pencil Drawing",
    "Water Coloring",
    "Quiz",
    "Reading Arabic",
    "Handwriting Arabic",
    "Qira'ath (girls)",
    "Hifz (girls)",
    "Calligraphy (girls)",
    "Kusumam Test (girls)",
    "Pencil Drawing (girls)",
    "Water Coloring (girls)",
    "Quiz (girls)",
    "Reading Arabic (girls)",
    "Handwriting Arabic (girls)",
  ],
  "LOWER-ZONE": [
    "Qira'ath",
    "Hifz",
    "Elocution Malayalam",
    "Madhu Ganam",
    "Storytelling",
    "Handwriting Arabic",
    "Malayalam",
    "Reading Arabic Malayalam",
    "Pencil Drawing",
    "Qira'ath (girls)",
    "Hifz (girls)",
    "Handwriting Arabic (girls)",
    "Malayalam (girls)",
    "Reading Arabic Malayalam (girls)",
    "Pencil Drawing (girls)",
  ],
  "RC MIX-ZONE": [
   'Sport Magazine',
   'Malappattu'

  ],
  "RC HI-ZONE": [
    "Qira'ath",
    "Hifz",
    "Speech ML",
    "Madh Song",
    "Speech ENG",
    "Essay ML",
    "Calligraphy"
  ],
  "RC MID-ZONE": [
    "Qira'ath",
    "Hifz",
    "Speech ML",
    "Madh Song",
    "Speech English",
    "Essay ML",
    "Calligraphy"
  ],
  "RC UPPER-ZONE": [
    "Qira'ath",
    "Hifz",
    "Speech ML",
    "Madh Song",
    "Story Telling",
    "Essay ML",
    "Pencil Drawing",
    "Water Colouring",
    "Calligraphy"
  ],
  "RC LOWER ZONE": [
    "Qira'ath",
    "Hifz",
    "Speech ML",
    "Madh Song",
    "Story Telling",
    "Essay ML",
    "Pencil Drawing",
    "Water Colouring",
    "Handwriting Arabic"
  ],
  "RC MIX-ZONE": [
    "Burdha",
    "Moulid",
    "Malappatt",
    "Qawwali",
    "Group Song",
    "Arabic Speech",
    "Nasheeda",
    "Essay ENG",
    "Essay ARB",
    "Arabic Language Game",
    "Ibarath Reading",
    "Hadees Musabaqa",
    "Spot Magazine",
    "Quiz Cat. A",
    "Quiz Cat. B",
    "Mappila Song Cat. A",
    "Mappila Song Cat. B",
    "Arabic Song"
  ]
};

const slides = [
  "https://res.cloudinary.com/do0mvctrk/image/upload/v1721982139/SSF_Kunnamangalam_Division_30th_Edition_Sahityotsav_2023July_01_02At_Kunnamangalam_sahityotsav2023_sahityotsav_30th_edition_arts_culture_literature_revolution_students_knowledge_competetion_winner_spi_zjcq6h.jpg",
  "https://res.cloudinary.com/do0mvctrk/image/upload/v1721982139/357480395_572652891493163_603989940549611415_n_nyk12s.jpg",
  "https://res.cloudinary.com/do0mvctrk/image/upload/v1721982139/358020129_2541173729369497_4997410294927867411_n_vudwn3.jpg",
  "https://res.cloudinary.com/do0mvctrk/image/upload/v1721982139/SSF_Kunnamangalam_Division_30th_Edition_Sahityotsav_2023July_01_02At_Kunnamangalam_sahityotsav2023_sahityotsav_30th_edition_arts_culture_literature_revolution_students_knowledge_competetion_winner_spi_zjcq6h.jpg",
  "https://res.cloudinary.com/do0mvctrk/image/upload/v1721982139/SSF_Kunnamangalam_Division_30th_Edition_Sahityotsav_2023July_01_02At_Kunnamangalam_sahityotsav2023_sahityotsav_30th_edition_arts_culture_literature_revolution_students_knowledge_competetion_winner_1_jwnfab.jpg",
  "https://res.cloudinary.com/do0mvctrk/image/upload/v1721982139/SSF_Kunnamangalam_Division_30th_Edition_Sahityotsav_2023July_01_02At_Kunnamangalam_sahityotsav2023_sahityotsav_30th_edition_arts_culture_literature_revolution_students_knowledge_competetion_winner_2_gywuvn.jpg",
  "https://res.cloudinary.com/do0mvctrk/image/upload/v1721982138/SSF_Kunnamangalam_Division_30th_Edition_Sahityotsav_2023July_01_02At_Kunnamangalam_sahityotsav2023_sahityotsav_30th_edition_arts_culture_literature_revolution_students_knowledge_competetion_winner_3_rh0wn1.jpg",
];
export { categories, sectors, itemsByCategory, slides };
